### ISSUE TITLE
State of Stock.Indicators v1.0.0

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators#104]
As many of you know, we're working towards a v1.0.0 version of this library.  I've recently [released v0.10.10](https://github.com/DaveSkender/Stock.Indicators/releases) with a number of changes based on feedback from a poll (#92).  While we will continue to add indicators before and after the v1.0.0 release, I'd like to consider this a major release candidate.  At this point, I do not expect to add any significant breaking changes and view the currently published package (v0.11.5) as production-ready.

With that said, I have a few things I'd like to do before flipping the version number:

- [x] Dogfood in my own trading system for a few weeks or more (in-progress)
- [x] Add performance benchmarking - [AB#727](https://dev.azure.com/skender/5123ca47-74f2-4d67-a5d4-c4d90b8d670a/_workitems/edit/727)
- [x] Further optimize performance of slower indicators (#114)
- [x] Add indicator chart images to documentation - [AB#717](https://dev.azure.com/skender/5123ca47-74f2-4d67-a5d4-c4d90b8d670a/_workitems/edit/717)
- [x] Incorporate any additional user concerns or ideas
- [x] Maybe add a few more indicators

Feedback appreciated.  Please comment below with your thoughts or [submit issues](https://github.com/DaveSkender/Stock.Indicators/issues) for any problems.  And if you want to help, [let me know](https://daveskender.github.io/Stock.Indicators/#contact-us).

**Comment by DaveSkender** [comment]
Package version 1.0.0 is now available in the public NuGet repository
